### ISSUE TITLE
Error with System.Collections.Stack

### ISSUE THREAD

**Issue by MarshMello0** [Bunny83/SimpleJSON#19]
When I download the files I have an error in SimpleJSON.cs.

The non-generic type 'Stack' cannot be used with type arguments
`Stack<JSONNode> stack = new Stack<JSONNode>();`

operator '==' cannot be applied to operands of type 'method group' and 'int'
`if (stack.Count == 0)`
`if (stack.Count > 0)`

**Comment by Bunny83** [comment]
Uhm, the file clearly uses the generic Stack class from the System.Collections.Generic namespace.

`using System.Collections.Generic;`

https://msdn.microsoft.com/en-us/library/3278tedw(v=vs.110).aspx

Where / how do you try to use it? What kind of project? I originally created this for normal .NET however I used it a lot in Unity3d which uses Mono.

Though in both cases the generic Stack class is defined in the "System.dll". Maybe your project does not references the System.dll? The generic Stack class exists since at least .NET version 2.0 ([so at least the last 12 years](https://en.wikipedia.org/wiki/.NET_Framework_version_history#.NET_Framework_2.0) ^^)

**Comment by Bunny83** [comment]
Not an issue. You most likely are missing the System.dll reference
