### ISSUE TITLE
License

### ISSUE THREAD

**Issue by opless** [Bunny83/SimpleJSON#2]
Hi,
I'm from the Unity wiki (same usename) and someone pointed me here regarding this issue:

see: https://github.com/opless/SimpleJSON/issues/1

Shall we merge any changes and come up to parity with licenses etc?

**Comment by NDark** [comment]
@Bunny83 


Hi, I'm NDark, a unity game developer. Sorry to bother, but I didn't found your contact.

I found your repository in surveying json libraries, and for some reason, I started to compare performance among different libraries.

Here is my so far result
https://github.com/NDark/ndinfrastructure/tree/P_JSONParsersPerformance

Are you Markus Göbel on http://wiki.unity3d.com/index.php/SimpleJSON ?

**Comment by Bunny83** [comment]
@NDark 

Yes, that's me. I've written SimpleJSON some time ago. However the version you seem to be using is a quite old version. It was a straight forward implementation back then without much edge cases in mind. The current version uses a cached StringBuilder for the "Escape" method. That way a ToString operation doesn't create tons of garbage when using very long string nodes.

Note that due to this change the ToString method is no longer thread-safe. Also if you consider switching keep in mind that the badly named "JSONClass" got renamed to "JSONObject".

ps: You should have opened a seperate Issue. This has not much to do with licencing.

**Comment by NDark** [comment]
Allright, cool, I derived your version from 2012, I've also modified the features you mentioned, but the version of 2017 is also good according to my test results.

Btw, don't need to open an new issue, I think, just need to know where I shall reference.
