### ISSUE TITLE
call ToString() method auto append " 

### ISSUE THREAD

**Issue by lyx32** [Bunny83/SimpleJSON#29]
Hi Bunny83。 I am coming again。
The same question as before。
But this time I modified the sample code and it works.

sample1

`
   
        String jsonString = "{\"id\":\"1\",\"name\":\"name-1\"}";
        JSONNode j = JSON.Parse(jsonText);
        String id1 = j["id"];                   // return 1
        String id2 = (String)j["id"];           // return 1
        String id3 = j["id"].ToString();        // return "1"
        String name1 = j["name"];               // return name-1
        String name2 = (String)j["name"];       // return name-1
        String name3 = j["name"].ToString();    // return "name-1"
`

sample2

`

        using (StreamReader sr = new StreamReader("D:\\json.txt"))
        {
            JSONNode j = JSON.Parse(sr.ReadToEnd());
            String id1 = j["id"];                   // return 111
            String id2 = (String)j["id"];           // return 111
            String id3 = j["id"].ToString();        // return "111"
            String name1 = j["name"];               // return json.text.name
            String name2 = (String)j["name"];       // return json.text.name
            String name3 = j["name"].ToString();    // return "json.text.name"
        }
`

file    "json.txt" content `
{"id":"111","name":"json.text.name"}
`

**Comment by Bunny83** [comment]
Well as I said the last time this is not an issue and is the expected behaviour.

Casting a JSONNode to string implicitly or explicitly will try to get the string **content** of that node. In case of a JSONString it will just return the string itself.

ToString on the other hand will convert the JSONNode back into **JSON**. So a [JSONString of course need to be quoted](https://www.json.org/json-en.html). Your proposed changes in [your other issue](https://github.com/Bunny83/SimpleJSON/issues/28) would completely break the serialization into JSON.

There are 3 ways how to read the **content** as a string:
```

string name1 = j["name"];  // implicit cast
string name2 = (string)j["name"];  // explicit cast
string name3 = j["name"].Value;  // the Value property

```
As said ToString will convert the node into json:

```
string json1 = j["name"].ToString();  // will return the JSONNode name serialized to inline JSON
string json2 = j["name"].ToString(3);  // will return the JSONNode name serialized to formatted JSON

```

**Comment by lyx32** [comment]
Oh, okay, I see what you mean.
But since you don't think what I said is a problem, So sorry to bother you.
Thank you for your answer.
I am translating English using translation software. If anything offends, please forgive me.
