### ISSUE TITLE
About the problem that'SimpleJson' cannot be used

### ISSUE THREAD

**Issue by RanX12** [Bunny83/SimpleJSON#43]
Hello, I use ```mcs **.cs && mono ./ **.exe``` to run the csharp program in docker, which uses ```SimpleJson```, but it will report an error, I want to ask about this What's the matter, is it because of missing commands in the command line? Please guide, thank you very much!

my Dockerfile：
![image](https://user-images.githubusercontent.com/46048444/107111351-7903cd80-688a-11eb-9735-d20938c05185.png)
![image](https://user-images.githubusercontent.com/46048444/107111358-815c0880-688a-11eb-95f4-32a8ef6f0207.png)

**Comment by Bunny83** [comment]
Sorry but I never have used docker ^^. What part of the SimpleJSON framework do you use? Keep in mind in that repository are several extension files which you may not use. For example the SimpleJSONUnity file only works when used in a Unity 3d project. When you just want the plain parser all you need is the SimpleJSON.cs file, nothing more.

You said 

> but it will report an error

this is very unspecific. What error do you get? I quickly added a conditional to the Unity extension file that should disable the Unity specific code, even when you include the Unity specific extension file in your project.

SimpleJSON itself does not require any external dependencies with the exception of the experimental compressed Binary format. Though the compression part is already guarded by a compiler switch that should [be commented out by default](https://github.com/Bunny83/SimpleJSON/blob/master/SimpleJSONBinary.cs#L1), so that shouldn't be an issue.

Are you actually sure that the project you talk about uses THIS SimpleJSON? There are other frameworks that are also called like that, but often capitalized differently. In your post you said "SimpleJson".

**Comment by Bunny83** [comment]
Since this doesn't seem to be related to SimpleJSON and I got no response I'll close this issue since there is no issue ^^.
