### ISSUE TITLE
"is" should be "=="

### ISSUE THREAD

**Issue by shadyasdf** [Bunny83/SimpleJSON#44]
https://github.com/Bunny83/SimpleJSON/blob/b0dd3c025ac89850f8e68835d519450a6fa37a12/SimpleJSON.cs#L366

**Comment by Bunny83** [comment]
Well, since C#7 there is the [constant support for the "is" operator](https://docs.microsoft.com/de-de/dotnet/csharp/language-reference/keywords/is#constant-pattern). So this is still valid code. Though I personally prefer an ordinary == operatir in such cases. It turns out the null support in that method was [added by someone else](https://github.com/Bunny83/SimpleJSON/commit/0ffec13c53e04f1cbe3b84a7599ea3afbf08ba7a#diff-e5f8092297dddae7c5bac60496f763c515d2a3f8753aaff8046518fabc47f74e).

I probably will replace it with a ==, though it shouldn't be an issue with the latest C# syntax.

**Comment by shadyasdf** [comment]
thanks 😄 

my use case is in an older version of Unity (2018.2.15f1) with the scripting runtime version set to ".NET 3.5 Equivalent", so definitely not as up-to-date as I should be, haha.
