### ISSUE TITLE
Examples?

### ISSUE THREAD

**Issue by sampepose** [Bunny83/SimpleJSON#8]
It'd be nice to see an example of parsing JSON to Unity types

**Comment by Bunny83** [comment]
Well, due to the implicit type conversion operators you can simply "assign" for example a Vector3 value at a place where a JSONNode is expected. Likewise you can directly assign a JSONNode (which represents a vector) to a vector3 variable.

```
JSONNode n = new JSONObject();
n["position"] = transform.position;

// reverse
Vector3 vec = n["position"];

```

Of course this only works where implicit conversion is possible. In cases where implicit conversion might not work you can always convert explicitly

`Vector3 vec = (Vector3)n["position"];`

So if you have JSON data which looks like this:
```

{
   "gameobjects": [
      {
         "prefabName": "cube",
         "name": "cube1",
         "position": [10,20,30],
         "rotation": [0,0,0],
         "scale": [1,1,1]
      },
      {
         "prefabName": "cube",
         "name": "cube2",
         "position": [20,20,30],
         "rotation": [0,45,0],
         "scale": [1,1,1]
      }
   ]
}
```

You can do something like that:

```
JSONNode data = JSON.Parse(theJSONText);
foreach(JSONNode obj in data["gameobjects"])
{
    GameObject prefab = GetPrefabByName(obj["prefabName"].Value);
    if (prefab != null)
    {
        var clone = Instantiate(prefab, obj["position"], Quaternion.Euler(obj["rotation"]));
        if (obj["scale"] != null)
            clone.transform.localScale = obj["scale"];
    }
}

```
Of course "GetPrefabByName" has to be provided by yourself. It's just a method that returns a prefab reference based on a string, maybe using a look up dictionary / prefab database.

**Comment by Shadowing1983** [comment]
I couldn't figure out how do you go from JSONNode to JSON?  
The wiki really needs more examples.
I"m doing this below to go from JSON to JSONNode but no where does it say to go from JSONNode to JSON
```
JSONNode json_object = JSON.Parse(response.DataAsText);
```

Also how do you create a empty JSONNode.
only way i could figure it out is to do

`JSONNode json_object = "{}";`

**Comment by Bunny83** [comment]
To convert a JSONNode tree back to json, just use `ToString()` on the node. It will create a compact json text (no spaces or new line characters). Alternatively you can use `ToString(number)` where "number" represents the wanted spaces for each layer to indent. e.g. `ToString(3)`

As for creating an "empty" JSONNode you have to know ahead of time what your node should represent since this framework uses strongly typed classes. In most cases you want to create either a JSONObject or a JSONArray like this:

`JSONNode root = new JSONObject();`

Everything else can be created through the lazy creator by doing things like

`root["someField"]["someSubField"].AsInt = 42;`

This would create something like this:

```
{
    "someField": {
        "someSubField" : 42
    }
}
```

Note that this line:

`JSONNode json_object = "{}";`

Will **not** create a JSONObject but rather a JSONString. That's because JSONNode has some implicit type conversion operators which will automatically turn int, float, double, ... into a JSONNumber, a string will be turned into a JSONString and a bool value like true or false will become a JSONBool.

Those [type conversion operators are defined here](https://github.com/Bunny83/SimpleJSON/blob/master/SimpleJSON.cs#L435)
